apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-probe
  name: backend-probe
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend-probe
  template:
    metadata:
      labels:
        app: backend-probe
    spec:
      containers:
#        - image: praqma/network-multitool:alpine-extra
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          name: {{ .Chart.Name }}
          ports:
            - name: http
              containerPort: {{ .Values.appPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

