apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app: backend-probe
spec:
  ports:
    - port: {{ .Values.appPort }}
      name: http
  selector:
    app: backend-probe
