# Front pod 4 prod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-prod
  labels:
    app: frontend-prod
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-prod
  template:
    metadata:
      labels:
        app: frontend-prod
    spec:
      containers:
      - name: client
        image: nginx:1.19
        ports:
        - containerPort: 80
        env:
        - name: BASE_URL
          value: backend-prod:9000
        volumeMounts:
        - name: nfs
          mountPath: /data   
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-prod
  namespace: default
spec:
  selector:
    app: frontend-prod
  ports:
    - name: frontend-prod
      protocol: TCP
      port: 8000
      targetPort: 80
  type: ClusterIP